import fs from 'node:fs'
import path from 'node:path'

import tailwindcss from '@tailwindcss/vite'
import react from '@vitejs/plugin-react'
import { defineConfig, type Plugin } from 'vite'

/**
 * main.go embeds frontend/dist, so the directory must exist in a fresh clone —
 * otherwise `go build`, `go test` and golangci-lint all fail with
 * "pattern all:frontend/dist: no matching files found" before anyone has built
 * the frontend. A committed .gitkeep solves that, but Vite empties outDir on
 * every build and deletes it. This puts it back.
 */
function keepDistTracked(): Plugin {
  return {
    name: 'keep-dist-tracked',
    apply: 'build',
    closeBundle() {
      fs.writeFileSync(path.resolve(import.meta.dirname, 'dist/.gitkeep'), '')
    },
  }
}

export default defineConfig({
  // Tailwind v4 runs as a Vite plugin. There is no postcss.config or
  // tailwind.config in v4 — theme lives in src/index.css via @theme.
  plugins: [react(), tailwindcss(), keepDistTracked()],
  resolve: {
    // Must stay in sync with "paths" in tsconfig.app.json; shadcn reads both
    // and fails to resolve components if they disagree.
    alias: {
      '@': path.resolve(import.meta.dirname, './src'),
      // Go bindings, regenerated by `wails generate module`.
      '@wails': path.resolve(import.meta.dirname, './wailsjs'),
    },
  },
})
