import path from 'node:path'

import tailwindcss from '@tailwindcss/vite'
import react from '@vitejs/plugin-react'
import { defineConfig } from 'vite'

export default defineConfig({
  // Tailwind v4 runs as a Vite plugin. There is no postcss.config or
  // tailwind.config in v4 — theme lives in src/index.css via @theme.
  plugins: [react(), tailwindcss()],
  resolve: {
    // Must stay in sync with the "paths" entry in tsconfig.json; shadcn reads
    // both and fails to resolve components if they disagree.
    alias: {
      '@': path.resolve(import.meta.dirname, './src'),
      // Go bindings, regenerated by `wails generate module`.
      '@wails': path.resolve(import.meta.dirname, './wailsjs'),
    },
  },
})
