// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package sqlc

import (
	"context"
)

const deletePinestemAccount = `-- name: DeletePinestemAccount :exec
DELETE FROM pinestem_account WHERE id = 1
`

func (q *Queries) DeletePinestemAccount(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deletePinestemAccount)
	return err
}

const deleteProfile = `-- name: DeleteProfile :exec
DELETE FROM app_profile WHERE id = 1
`

func (q *Queries) DeleteProfile(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteProfile)
	return err
}

const getPinestemAccount = `-- name: GetPinestemAccount :one
SELECT id, user_id, user_name, first_name, last_name, company_id, company_name, role_id, is_project_manager, is_team_lead, account_type, time_zone, date_time_format, authenticated_at, token_fallback FROM pinestem_account WHERE id = 1
`

func (q *Queries) GetPinestemAccount(ctx context.Context) (PinestemAccount, error) {
	row := q.db.QueryRowContext(ctx, getPinestemAccount)
	var i PinestemAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UserName,
		&i.FirstName,
		&i.LastName,
		&i.CompanyID,
		&i.CompanyName,
		&i.RoleID,
		&i.IsProjectManager,
		&i.IsTeamLead,
		&i.AccountType,
		&i.TimeZone,
		&i.DateTimeFormat,
		&i.AuthenticatedAt,
		&i.TokenFallback,
	)
	return i, err
}

const getProfile = `-- name: GetProfile :one
SELECT id, display_name, created_at, updated_at FROM app_profile WHERE id = 1
`

func (q *Queries) GetProfile(ctx context.Context) (AppProfile, error) {
	row := q.db.QueryRowContext(ctx, getProfile)
	var i AppProfile
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPinestemAccount = `-- name: UpsertPinestemAccount :exec
INSERT INTO pinestem_account (
    id, user_id, user_name, first_name, last_name,
    company_id, company_name, role_id,
    is_project_manager, is_team_lead,
    account_type, time_zone, date_time_format,
    authenticated_at, token_fallback
) VALUES (1, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    user_id            = excluded.user_id,
    user_name          = excluded.user_name,
    first_name         = excluded.first_name,
    last_name          = excluded.last_name,
    company_id         = excluded.company_id,
    company_name       = excluded.company_name,
    role_id            = excluded.role_id,
    is_project_manager = excluded.is_project_manager,
    is_team_lead       = excluded.is_team_lead,
    account_type       = excluded.account_type,
    time_zone          = excluded.time_zone,
    date_time_format   = excluded.date_time_format,
    authenticated_at   = excluded.authenticated_at,
    token_fallback     = excluded.token_fallback
`

type UpsertPinestemAccountParams struct {
	UserID           int64   `json:"user_id"`
	UserName         string  `json:"user_name"`
	FirstName        string  `json:"first_name"`
	LastName         string  `json:"last_name"`
	CompanyID        int64   `json:"company_id"`
	CompanyName      string  `json:"company_name"`
	RoleID           int64   `json:"role_id"`
	IsProjectManager int64   `json:"is_project_manager"`
	IsTeamLead       int64   `json:"is_team_lead"`
	AccountType      string  `json:"account_type"`
	TimeZone         string  `json:"time_zone"`
	DateTimeFormat   string  `json:"date_time_format"`
	AuthenticatedAt  string  `json:"authenticated_at"`
	TokenFallback    *string `json:"token_fallback"`
}

func (q *Queries) UpsertPinestemAccount(ctx context.Context, arg UpsertPinestemAccountParams) error {
	_, err := q.db.ExecContext(ctx, upsertPinestemAccount,
		arg.UserID,
		arg.UserName,
		arg.FirstName,
		arg.LastName,
		arg.CompanyID,
		arg.CompanyName,
		arg.RoleID,
		arg.IsProjectManager,
		arg.IsTeamLead,
		arg.AccountType,
		arg.TimeZone,
		arg.DateTimeFormat,
		arg.AuthenticatedAt,
		arg.TokenFallback,
	)
	return err
}

const upsertProfile = `-- name: UpsertProfile :exec
INSERT INTO app_profile (id, display_name, created_at, updated_at)
VALUES (1, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    display_name = excluded.display_name,
    updated_at   = excluded.updated_at
`

type UpsertProfileParams struct {
	DisplayName string `json:"display_name"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

func (q *Queries) UpsertProfile(ctx context.Context, arg UpsertProfileParams) error {
	_, err := q.db.ExecContext(ctx, upsertProfile, arg.DisplayName, arg.CreatedAt, arg.UpdatedAt)
	return err
}
