// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

type AppProfile struct {
	ID          int64  `json:"id"`
	DisplayName string `json:"display_name"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

type AppSetting struct {
	ID                            int64   `json:"id"`
	RefreshIntervalSeconds        int64   `json:"refresh_interval_seconds"`
	TasksSyncedAt                 *string `json:"tasks_synced_at"`
	NotifyNewTasks                int64   `json:"notify_new_tasks"`
	FocusOnNewTask                int64   `json:"focus_on_new_task"`
	BillingRefreshIntervalSeconds int64   `json:"billing_refresh_interval_seconds"`
	WeekStartDay                  int64   `json:"week_start_day"`
	BillingSyncedAt               *string `json:"billing_synced_at"`
	NotificationTimeoutSeconds    int64   `json:"notification_timeout_seconds"`
	MonitorsSyncedAt              *string `json:"monitors_synced_at"`
	MyTasksRefreshIntervalSeconds int64   `json:"my_tasks_refresh_interval_seconds"`
	NotifyNewMyTasks              int64   `json:"notify_new_my_tasks"`
	MyTasksSyncedAt               *string `json:"my_tasks_synced_at"`
}

type BillingDay struct {
	Day                string `json:"day"`
	BillableMinutes    int64  `json:"billable_minutes"`
	NonBillableMinutes int64  `json:"non_billable_minutes"`
}

type HiddenMyTask struct {
	TaskID    int64  `json:"task_id"`
	ShortCode string `json:"short_code"`
	Name      string `json:"name"`
	HiddenAt  string `json:"hidden_at"`
}

type Monitor struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type MonitorActual struct {
	MonitorID          int64 `json:"monitor_id"`
	EmpID              int64 `json:"emp_id"`
	ProjectID          int64 `json:"project_id"`
	BillableMinutes    int64 `json:"billable_minutes"`
	NonBillableMinutes int64 `json:"non_billable_minutes"`
}

type MonitorProject struct {
	MonitorID   int64  `json:"monitor_id"`
	ProjectID   int64  `json:"project_id"`
	ProjectCode string `json:"project_code"`
	ProjectName string `json:"project_name"`
}

type MonitorTarget struct {
	MonitorID     int64  `json:"monitor_id"`
	EmpID         int64  `json:"emp_id"`
	EmpName       string `json:"emp_name"`
	ProjectID     int64  `json:"project_id"`
	TargetMinutes int64  `json:"target_minutes"`
}

type MyTask struct {
	TaskID         int64  `json:"task_id"`
	ShortCode      string `json:"short_code"`
	Name           string `json:"name"`
	ProjectCode    string `json:"project_code"`
	ProjectName    string `json:"project_name"`
	Priority       string `json:"priority"`
	StatusID       int64  `json:"status_id"`
	StatusType     string `json:"status_type"`
	StatusColor    string `json:"status_color"`
	DueDate        string `json:"due_date"`
	ModifiedOn     string `json:"modified_on"`
	SprintName     string `json:"sprint_name"`
	CompetencyName string `json:"competency_name"`
	SyncedAt       string `json:"synced_at"`
}

type MyTaskProjectFilter struct {
	ProjectCode string `json:"project_code"`
	ProjectName string `json:"project_name"`
}

type MyTaskStatusFilter struct {
	StatusID   int64  `json:"status_id"`
	StatusName string `json:"status_name"`
}

type PinestemAccount struct {
	ID               int64   `json:"id"`
	UserID           int64   `json:"user_id"`
	UserName         string  `json:"user_name"`
	FirstName        string  `json:"first_name"`
	LastName         string  `json:"last_name"`
	CompanyID        int64   `json:"company_id"`
	CompanyName      string  `json:"company_name"`
	RoleID           int64   `json:"role_id"`
	IsProjectManager int64   `json:"is_project_manager"`
	IsTeamLead       int64   `json:"is_team_lead"`
	AccountType      string  `json:"account_type"`
	TimeZone         string  `json:"time_zone"`
	DateTimeFormat   string  `json:"date_time_format"`
	AuthenticatedAt  string  `json:"authenticated_at"`
	TokenFallback    *string `json:"token_fallback"`
}

type Project struct {
	ProjectID int64  `json:"project_id"`
	Code      string `json:"code"`
	Name      string `json:"name"`
	StatusID  int64  `json:"status_id"`
}

type SeenMyTask struct {
	TaskID       int64  `json:"task_id"`
	FirstSeenAt  string `json:"first_seen_at"`
	Acknowledged int64  `json:"acknowledged"`
}

type SeenTask struct {
	TaskID       int64  `json:"task_id"`
	FirstSeenAt  string `json:"first_seen_at"`
	Acknowledged int64  `json:"acknowledged"`
}

type Task struct {
	TaskID         int64  `json:"task_id"`
	ShortCode      string `json:"short_code"`
	Name           string `json:"name"`
	ProjectCode    string `json:"project_code"`
	ProjectName    string `json:"project_name"`
	Priority       string `json:"priority"`
	StatusType     string `json:"status_type"`
	StatusColor    string `json:"status_color"`
	DueDate        string `json:"due_date"`
	ModifiedOn     string `json:"modified_on"`
	SprintName     string `json:"sprint_name"`
	CompetencyName string `json:"competency_name"`
	SyncedAt       string `json:"synced_at"`
}
