// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

type AppProfile struct {
	ID          int64  `json:"id"`
	DisplayName string `json:"display_name"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

type PinestemAccount struct {
	ID               int64   `json:"id"`
	UserID           int64   `json:"user_id"`
	UserName         string  `json:"user_name"`
	FirstName        string  `json:"first_name"`
	LastName         string  `json:"last_name"`
	CompanyID        int64   `json:"company_id"`
	CompanyName      string  `json:"company_name"`
	RoleID           int64   `json:"role_id"`
	IsProjectManager int64   `json:"is_project_manager"`
	IsTeamLead       int64   `json:"is_team_lead"`
	AccountType      string  `json:"account_type"`
	TimeZone         string  `json:"time_zone"`
	DateTimeFormat   string  `json:"date_time_format"`
	AuthenticatedAt  string  `json:"authenticated_at"`
	TokenFallback    *string `json:"token_fallback"`
}
