// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

type AppProfile struct {
	ID          int64  `json:"id"`
	DisplayName string `json:"display_name"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

type AppSetting struct {
	ID                     int64   `json:"id"`
	RefreshIntervalSeconds int64   `json:"refresh_interval_seconds"`
	TasksSyncedAt          *string `json:"tasks_synced_at"`
}

type PinestemAccount struct {
	ID               int64   `json:"id"`
	UserID           int64   `json:"user_id"`
	UserName         string  `json:"user_name"`
	FirstName        string  `json:"first_name"`
	LastName         string  `json:"last_name"`
	CompanyID        int64   `json:"company_id"`
	CompanyName      string  `json:"company_name"`
	RoleID           int64   `json:"role_id"`
	IsProjectManager int64   `json:"is_project_manager"`
	IsTeamLead       int64   `json:"is_team_lead"`
	AccountType      string  `json:"account_type"`
	TimeZone         string  `json:"time_zone"`
	DateTimeFormat   string  `json:"date_time_format"`
	AuthenticatedAt  string  `json:"authenticated_at"`
	TokenFallback    *string `json:"token_fallback"`
}

type Project struct {
	ProjectID int64  `json:"project_id"`
	Code      string `json:"code"`
	Name      string `json:"name"`
	StatusID  int64  `json:"status_id"`
}

type Task struct {
	TaskID         int64  `json:"task_id"`
	ShortCode      string `json:"short_code"`
	Name           string `json:"name"`
	ProjectCode    string `json:"project_code"`
	ProjectName    string `json:"project_name"`
	Priority       string `json:"priority"`
	StatusType     string `json:"status_type"`
	StatusColor    string `json:"status_color"`
	DueDate        string `json:"due_date"`
	ModifiedOn     string `json:"modified_on"`
	SprintName     string `json:"sprint_name"`
	CompetencyName string `json:"competency_name"`
	SyncedAt       string `json:"synced_at"`
}
