// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: monitors.sql

package sqlc

import (
	"context"
)

const deleteAllMonitorActuals = `-- name: DeleteAllMonitorActuals :exec
DELETE FROM monitor_actual
`

func (q *Queries) DeleteAllMonitorActuals(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllMonitorActuals)
	return err
}

const deleteMonitor = `-- name: DeleteMonitor :exec
DELETE FROM monitor WHERE id = ?
`

func (q *Queries) DeleteMonitor(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteMonitor, id)
	return err
}

const deleteMonitorProjects = `-- name: DeleteMonitorProjects :exec
DELETE FROM monitor_project WHERE monitor_id = ?
`

func (q *Queries) DeleteMonitorProjects(ctx context.Context, monitorID int64) error {
	_, err := q.db.ExecContext(ctx, deleteMonitorProjects, monitorID)
	return err
}

const deleteMonitorTargets = `-- name: DeleteMonitorTargets :exec
DELETE FROM monitor_target WHERE monitor_id = ?
`

func (q *Queries) DeleteMonitorTargets(ctx context.Context, monitorID int64) error {
	_, err := q.db.ExecContext(ctx, deleteMonitorTargets, monitorID)
	return err
}

const getMonitor = `-- name: GetMonitor :one
SELECT id, name, created_at, updated_at FROM monitor WHERE id = ?
`

func (q *Queries) GetMonitor(ctx context.Context, id int64) (Monitor, error) {
	row := q.db.QueryRowContext(ctx, getMonitor, id)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertMonitor = `-- name: InsertMonitor :one
INSERT INTO monitor (name, created_at, updated_at) VALUES (?, ?, ?)
RETURNING id
`

type InsertMonitorParams struct {
	Name      string `json:"name"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

func (q *Queries) InsertMonitor(ctx context.Context, arg InsertMonitorParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertMonitor, arg.Name, arg.CreatedAt, arg.UpdatedAt)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertMonitorActual = `-- name: InsertMonitorActual :exec
INSERT INTO monitor_actual (
    monitor_id, emp_id, project_id, billable_minutes, non_billable_minutes
) VALUES (?, ?, ?, ?, ?)
`

type InsertMonitorActualParams struct {
	MonitorID          int64 `json:"monitor_id"`
	EmpID              int64 `json:"emp_id"`
	ProjectID          int64 `json:"project_id"`
	BillableMinutes    int64 `json:"billable_minutes"`
	NonBillableMinutes int64 `json:"non_billable_minutes"`
}

func (q *Queries) InsertMonitorActual(ctx context.Context, arg InsertMonitorActualParams) error {
	_, err := q.db.ExecContext(ctx, insertMonitorActual,
		arg.MonitorID,
		arg.EmpID,
		arg.ProjectID,
		arg.BillableMinutes,
		arg.NonBillableMinutes,
	)
	return err
}

const insertMonitorProject = `-- name: InsertMonitorProject :exec
INSERT INTO monitor_project (monitor_id, project_id, project_code, project_name)
VALUES (?, ?, ?, ?)
`

type InsertMonitorProjectParams struct {
	MonitorID   int64  `json:"monitor_id"`
	ProjectID   int64  `json:"project_id"`
	ProjectCode string `json:"project_code"`
	ProjectName string `json:"project_name"`
}

func (q *Queries) InsertMonitorProject(ctx context.Context, arg InsertMonitorProjectParams) error {
	_, err := q.db.ExecContext(ctx, insertMonitorProject,
		arg.MonitorID,
		arg.ProjectID,
		arg.ProjectCode,
		arg.ProjectName,
	)
	return err
}

const insertMonitorTarget = `-- name: InsertMonitorTarget :exec
INSERT INTO monitor_target (monitor_id, emp_id, emp_name, project_id, target_minutes)
VALUES (?, ?, ?, ?, ?)
`

type InsertMonitorTargetParams struct {
	MonitorID     int64  `json:"monitor_id"`
	EmpID         int64  `json:"emp_id"`
	EmpName       string `json:"emp_name"`
	ProjectID     int64  `json:"project_id"`
	TargetMinutes int64  `json:"target_minutes"`
}

func (q *Queries) InsertMonitorTarget(ctx context.Context, arg InsertMonitorTargetParams) error {
	_, err := q.db.ExecContext(ctx, insertMonitorTarget,
		arg.MonitorID,
		arg.EmpID,
		arg.EmpName,
		arg.ProjectID,
		arg.TargetMinutes,
	)
	return err
}

const listMonitorActuals = `-- name: ListMonitorActuals :many
SELECT monitor_id, emp_id, project_id, billable_minutes, non_billable_minutes FROM monitor_actual
`

func (q *Queries) ListMonitorActuals(ctx context.Context) ([]MonitorActual, error) {
	rows, err := q.db.QueryContext(ctx, listMonitorActuals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MonitorActual{}
	for rows.Next() {
		var i MonitorActual
		if err := rows.Scan(
			&i.MonitorID,
			&i.EmpID,
			&i.ProjectID,
			&i.BillableMinutes,
			&i.NonBillableMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonitorProjects = `-- name: ListMonitorProjects :many
SELECT monitor_id, project_id, project_code, project_name FROM monitor_project ORDER BY monitor_id, project_code
`

func (q *Queries) ListMonitorProjects(ctx context.Context) ([]MonitorProject, error) {
	rows, err := q.db.QueryContext(ctx, listMonitorProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MonitorProject{}
	for rows.Next() {
		var i MonitorProject
		if err := rows.Scan(
			&i.MonitorID,
			&i.ProjectID,
			&i.ProjectCode,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonitorTargets = `-- name: ListMonitorTargets :many
SELECT monitor_id, emp_id, emp_name, project_id, target_minutes FROM monitor_target ORDER BY monitor_id, emp_name, project_id
`

func (q *Queries) ListMonitorTargets(ctx context.Context) ([]MonitorTarget, error) {
	rows, err := q.db.QueryContext(ctx, listMonitorTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MonitorTarget{}
	for rows.Next() {
		var i MonitorTarget
		if err := rows.Scan(
			&i.MonitorID,
			&i.EmpID,
			&i.EmpName,
			&i.ProjectID,
			&i.TargetMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonitors = `-- name: ListMonitors :many
SELECT id, name, created_at, updated_at FROM monitor ORDER BY name
`

func (q *Queries) ListMonitors(ctx context.Context) ([]Monitor, error) {
	rows, err := q.db.QueryContext(ctx, listMonitors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Monitor{}
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMonitorsSyncedAt = `-- name: SetMonitorsSyncedAt :exec
INSERT INTO app_settings (id, monitors_synced_at)
VALUES (1, ?)
ON CONFLICT(id) DO UPDATE SET monitors_synced_at = excluded.monitors_synced_at
`

func (q *Queries) SetMonitorsSyncedAt(ctx context.Context, monitorsSyncedAt *string) error {
	_, err := q.db.ExecContext(ctx, setMonitorsSyncedAt, monitorsSyncedAt)
	return err
}

const updateMonitor = `-- name: UpdateMonitor :exec
UPDATE monitor SET name = ?, updated_at = ? WHERE id = ?
`

type UpdateMonitorParams struct {
	Name      string `json:"name"`
	UpdatedAt string `json:"updated_at"`
	ID        int64  `json:"id"`
}

func (q *Queries) UpdateMonitor(ctx context.Context, arg UpdateMonitorParams) error {
	_, err := q.db.ExecContext(ctx, updateMonitor, arg.Name, arg.UpdatedAt, arg.ID)
	return err
}
