// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: my_tasks.sql

package sqlc

import (
	"context"
)

const acknowledgeAllMyTasks = `-- name: AcknowledgeAllMyTasks :exec
UPDATE seen_my_task SET acknowledged = 1
`

func (q *Queries) AcknowledgeAllMyTasks(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, acknowledgeAllMyTasks)
	return err
}

const acknowledgeMyTask = `-- name: AcknowledgeMyTask :exec
UPDATE seen_my_task SET acknowledged = 1 WHERE task_id = ?
`

func (q *Queries) AcknowledgeMyTask(ctx context.Context, taskID int64) error {
	_, err := q.db.ExecContext(ctx, acknowledgeMyTask, taskID)
	return err
}

const deleteAllMyTasks = `-- name: DeleteAllMyTasks :exec
DELETE FROM my_task
`

func (q *Queries) DeleteAllMyTasks(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllMyTasks)
	return err
}

const deleteAllSeenMyTasks = `-- name: DeleteAllSeenMyTasks :exec
DELETE FROM seen_my_task
`

func (q *Queries) DeleteAllSeenMyTasks(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllSeenMyTasks)
	return err
}

const deleteMyTaskProjectFilter = `-- name: DeleteMyTaskProjectFilter :exec
DELETE FROM my_task_project_filter
`

func (q *Queries) DeleteMyTaskProjectFilter(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteMyTaskProjectFilter)
	return err
}

const deleteMyTaskStatusFilter = `-- name: DeleteMyTaskStatusFilter :exec
DELETE FROM my_task_status_filter
`

func (q *Queries) DeleteMyTaskStatusFilter(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteMyTaskStatusFilter)
	return err
}

const hideMyTask = `-- name: HideMyTask :exec
INSERT INTO hidden_my_task (task_id, short_code, name, hidden_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(task_id) DO UPDATE SET
    short_code = excluded.short_code,
    name       = excluded.name,
    hidden_at  = excluded.hidden_at
`

type HideMyTaskParams struct {
	TaskID    int64  `json:"task_id"`
	ShortCode string `json:"short_code"`
	Name      string `json:"name"`
	HiddenAt  string `json:"hidden_at"`
}

// Re-hiding an already hidden task refreshes its labels rather than failing.
func (q *Queries) HideMyTask(ctx context.Context, arg HideMyTaskParams) error {
	_, err := q.db.ExecContext(ctx, hideMyTask,
		arg.TaskID,
		arg.ShortCode,
		arg.Name,
		arg.HiddenAt,
	)
	return err
}

const insertMyTask = `-- name: InsertMyTask :exec
INSERT INTO my_task (
    task_id, short_code, name, project_code, project_name,
    priority, status_id, status_type, status_color,
    due_date, modified_on, sprint_name, competency_name, synced_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertMyTaskParams struct {
	TaskID         int64  `json:"task_id"`
	ShortCode      string `json:"short_code"`
	Name           string `json:"name"`
	ProjectCode    string `json:"project_code"`
	ProjectName    string `json:"project_name"`
	Priority       string `json:"priority"`
	StatusID       int64  `json:"status_id"`
	StatusType     string `json:"status_type"`
	StatusColor    string `json:"status_color"`
	DueDate        string `json:"due_date"`
	ModifiedOn     string `json:"modified_on"`
	SprintName     string `json:"sprint_name"`
	CompetencyName string `json:"competency_name"`
	SyncedAt       string `json:"synced_at"`
}

func (q *Queries) InsertMyTask(ctx context.Context, arg InsertMyTaskParams) error {
	_, err := q.db.ExecContext(ctx, insertMyTask,
		arg.TaskID,
		arg.ShortCode,
		arg.Name,
		arg.ProjectCode,
		arg.ProjectName,
		arg.Priority,
		arg.StatusID,
		arg.StatusType,
		arg.StatusColor,
		arg.DueDate,
		arg.ModifiedOn,
		arg.SprintName,
		arg.CompetencyName,
		arg.SyncedAt,
	)
	return err
}

const insertMyTaskProjectFilter = `-- name: InsertMyTaskProjectFilter :exec
INSERT INTO my_task_project_filter (project_code, project_name) VALUES (?, ?)
`

type InsertMyTaskProjectFilterParams struct {
	ProjectCode string `json:"project_code"`
	ProjectName string `json:"project_name"`
}

func (q *Queries) InsertMyTaskProjectFilter(ctx context.Context, arg InsertMyTaskProjectFilterParams) error {
	_, err := q.db.ExecContext(ctx, insertMyTaskProjectFilter, arg.ProjectCode, arg.ProjectName)
	return err
}

const insertMyTaskStatusFilter = `-- name: InsertMyTaskStatusFilter :exec
INSERT INTO my_task_status_filter (status_id, status_name) VALUES (?, ?)
`

type InsertMyTaskStatusFilterParams struct {
	StatusID   int64  `json:"status_id"`
	StatusName string `json:"status_name"`
}

func (q *Queries) InsertMyTaskStatusFilter(ctx context.Context, arg InsertMyTaskStatusFilterParams) error {
	_, err := q.db.ExecContext(ctx, insertMyTaskStatusFilter, arg.StatusID, arg.StatusName)
	return err
}

const insertSeenMyTask = `-- name: InsertSeenMyTask :exec
INSERT INTO seen_my_task (task_id, first_seen_at, acknowledged) VALUES (?, ?, ?)
`

type InsertSeenMyTaskParams struct {
	TaskID       int64  `json:"task_id"`
	FirstSeenAt  string `json:"first_seen_at"`
	Acknowledged int64  `json:"acknowledged"`
}

func (q *Queries) InsertSeenMyTask(ctx context.Context, arg InsertSeenMyTaskParams) error {
	_, err := q.db.ExecContext(ctx, insertSeenMyTask, arg.TaskID, arg.FirstSeenAt, arg.Acknowledged)
	return err
}

const listHiddenMyTasks = `-- name: ListHiddenMyTasks :many
SELECT task_id, short_code, name, hidden_at FROM hidden_my_task ORDER BY hidden_at DESC
`

func (q *Queries) ListHiddenMyTasks(ctx context.Context) ([]HiddenMyTask, error) {
	rows, err := q.db.QueryContext(ctx, listHiddenMyTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HiddenMyTask{}
	for rows.Next() {
		var i HiddenMyTask
		if err := rows.Scan(
			&i.TaskID,
			&i.ShortCode,
			&i.Name,
			&i.HiddenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyTaskProjectFilter = `-- name: ListMyTaskProjectFilter :many
SELECT project_code, project_name FROM my_task_project_filter ORDER BY project_code
`

func (q *Queries) ListMyTaskProjectFilter(ctx context.Context) ([]MyTaskProjectFilter, error) {
	rows, err := q.db.QueryContext(ctx, listMyTaskProjectFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MyTaskProjectFilter{}
	for rows.Next() {
		var i MyTaskProjectFilter
		if err := rows.Scan(&i.ProjectCode, &i.ProjectName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyTaskStatusFilter = `-- name: ListMyTaskStatusFilter :many
SELECT status_id, status_name FROM my_task_status_filter ORDER BY status_name
`

func (q *Queries) ListMyTaskStatusFilter(ctx context.Context) ([]MyTaskStatusFilter, error) {
	rows, err := q.db.QueryContext(ctx, listMyTaskStatusFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MyTaskStatusFilter{}
	for rows.Next() {
		var i MyTaskStatusFilter
		if err := rows.Scan(&i.StatusID, &i.StatusName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyTasks = `-- name: ListMyTasks :many
SELECT
    t.task_id, t.short_code, t.name, t.project_code, t.project_name, t.priority, t.status_id, t.status_type, t.status_color, t.due_date, t.modified_on, t.sprint_name, t.competency_name, t.synced_at,
    COALESCE(s.acknowledged, 1) AS acknowledged,
    CASE WHEN h.task_id IS NULL THEN 0 ELSE 1 END AS hidden
FROM my_task t
LEFT JOIN seen_my_task s ON s.task_id = t.task_id
LEFT JOIN hidden_my_task h ON h.task_id = t.task_id
ORDER BY
    CASE WHEN t.due_date = '' THEN 1 ELSE 0 END,
    t.due_date,
    t.modified_on DESC
`

type ListMyTasksRow struct {
	TaskID         int64  `json:"task_id"`
	ShortCode      string `json:"short_code"`
	Name           string `json:"name"`
	ProjectCode    string `json:"project_code"`
	ProjectName    string `json:"project_name"`
	Priority       string `json:"priority"`
	StatusID       int64  `json:"status_id"`
	StatusType     string `json:"status_type"`
	StatusColor    string `json:"status_color"`
	DueDate        string `json:"due_date"`
	ModifiedOn     string `json:"modified_on"`
	SprintName     string `json:"sprint_name"`
	CompetencyName string `json:"competency_name"`
	SyncedAt       string `json:"synced_at"`
	Acknowledged   int64  `json:"acknowledged"`
	Hidden         int64  `json:"hidden"`
}

// Soonest due first, undated last, newest-modified breaking ties. Both flags are
// COALESCEd to the safe default: an unknown task is "already seen" (never a
// surprise highlight) and not hidden.
func (q *Queries) ListMyTasks(ctx context.Context) ([]ListMyTasksRow, error) {
	rows, err := q.db.QueryContext(ctx, listMyTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyTasksRow{}
	for rows.Next() {
		var i ListMyTasksRow
		if err := rows.Scan(
			&i.TaskID,
			&i.ShortCode,
			&i.Name,
			&i.ProjectCode,
			&i.ProjectName,
			&i.Priority,
			&i.StatusID,
			&i.StatusType,
			&i.StatusColor,
			&i.DueDate,
			&i.ModifiedOn,
			&i.SprintName,
			&i.CompetencyName,
			&i.SyncedAt,
			&i.Acknowledged,
			&i.Hidden,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeenMyTasks = `-- name: ListSeenMyTasks :many
SELECT task_id, first_seen_at, acknowledged FROM seen_my_task
`

func (q *Queries) ListSeenMyTasks(ctx context.Context) ([]SeenMyTask, error) {
	rows, err := q.db.QueryContext(ctx, listSeenMyTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SeenMyTask{}
	for rows.Next() {
		var i SeenMyTask
		if err := rows.Scan(&i.TaskID, &i.FirstSeenAt, &i.Acknowledged); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMyTasksSyncedAt = `-- name: SetMyTasksSyncedAt :exec
INSERT INTO app_settings (id, my_tasks_synced_at)
VALUES (1, ?)
ON CONFLICT(id) DO UPDATE SET my_tasks_synced_at = excluded.my_tasks_synced_at
`

func (q *Queries) SetMyTasksSyncedAt(ctx context.Context, myTasksSyncedAt *string) error {
	_, err := q.db.ExecContext(ctx, setMyTasksSyncedAt, myTasksSyncedAt)
	return err
}

const unhideAllMyTasks = `-- name: UnhideAllMyTasks :exec
DELETE FROM hidden_my_task
`

func (q *Queries) UnhideAllMyTasks(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, unhideAllMyTasks)
	return err
}

const unhideMyTask = `-- name: UnhideMyTask :exec
DELETE FROM hidden_my_task WHERE task_id = ?
`

func (q *Queries) UnhideMyTask(ctx context.Context, taskID int64) error {
	_, err := q.db.ExecContext(ctx, unhideMyTask, taskID)
	return err
}
