// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	DeletePinestemAccount(ctx context.Context) error
	DeleteProfile(ctx context.Context) error
	GetPinestemAccount(ctx context.Context) (PinestemAccount, error)
	GetProfile(ctx context.Context) (AppProfile, error)
	UpsertPinestemAccount(ctx context.Context, arg UpsertPinestemAccountParams) error
	UpsertProfile(ctx context.Context, arg UpsertProfileParams) error
}

var _ Querier = (*Queries)(nil)
