// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package sqlc

import (
	"context"
)

const deleteAllProjects = `-- name: DeleteAllProjects :exec
DELETE FROM project
`

func (q *Queries) DeleteAllProjects(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllProjects)
	return err
}

const deleteAllTasks = `-- name: DeleteAllTasks :exec
DELETE FROM task
`

func (q *Queries) DeleteAllTasks(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllTasks)
	return err
}

const getSettings = `-- name: GetSettings :one
SELECT id, refresh_interval_seconds, tasks_synced_at FROM app_settings WHERE id = 1
`

func (q *Queries) GetSettings(ctx context.Context) (AppSetting, error) {
	row := q.db.QueryRowContext(ctx, getSettings)
	var i AppSetting
	err := row.Scan(&i.ID, &i.RefreshIntervalSeconds, &i.TasksSyncedAt)
	return i, err
}

const insertProject = `-- name: InsertProject :exec
INSERT INTO project (project_id, code, name, status_id)
VALUES (?, ?, ?, ?)
`

type InsertProjectParams struct {
	ProjectID int64  `json:"project_id"`
	Code      string `json:"code"`
	Name      string `json:"name"`
	StatusID  int64  `json:"status_id"`
}

func (q *Queries) InsertProject(ctx context.Context, arg InsertProjectParams) error {
	_, err := q.db.ExecContext(ctx, insertProject,
		arg.ProjectID,
		arg.Code,
		arg.Name,
		arg.StatusID,
	)
	return err
}

const insertTask = `-- name: InsertTask :exec
INSERT INTO task (
    task_id, short_code, name, project_code, project_name,
    priority, status_type, status_color,
    due_date, modified_on, sprint_name, competency_name, synced_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertTaskParams struct {
	TaskID         int64  `json:"task_id"`
	ShortCode      string `json:"short_code"`
	Name           string `json:"name"`
	ProjectCode    string `json:"project_code"`
	ProjectName    string `json:"project_name"`
	Priority       string `json:"priority"`
	StatusType     string `json:"status_type"`
	StatusColor    string `json:"status_color"`
	DueDate        string `json:"due_date"`
	ModifiedOn     string `json:"modified_on"`
	SprintName     string `json:"sprint_name"`
	CompetencyName string `json:"competency_name"`
	SyncedAt       string `json:"synced_at"`
}

func (q *Queries) InsertTask(ctx context.Context, arg InsertTaskParams) error {
	_, err := q.db.ExecContext(ctx, insertTask,
		arg.TaskID,
		arg.ShortCode,
		arg.Name,
		arg.ProjectCode,
		arg.ProjectName,
		arg.Priority,
		arg.StatusType,
		arg.StatusColor,
		arg.DueDate,
		arg.ModifiedOn,
		arg.SprintName,
		arg.CompetencyName,
		arg.SyncedAt,
	)
	return err
}

const listProjects = `-- name: ListProjects :many
SELECT project_id, code, name, status_id FROM project ORDER BY code
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ProjectID,
			&i.Code,
			&i.Name,
			&i.StatusID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT task_id, short_code, name, project_code, project_name, priority, status_type, status_color, due_date, modified_on, sprint_name, competency_name, synced_at FROM task ORDER BY modified_on DESC
`

func (q *Queries) ListTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.TaskID,
			&i.ShortCode,
			&i.Name,
			&i.ProjectCode,
			&i.ProjectName,
			&i.Priority,
			&i.StatusType,
			&i.StatusColor,
			&i.DueDate,
			&i.ModifiedOn,
			&i.SprintName,
			&i.CompetencyName,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRefreshInterval = `-- name: SetRefreshInterval :exec
INSERT INTO app_settings (id, refresh_interval_seconds)
VALUES (1, ?)
ON CONFLICT(id) DO UPDATE SET refresh_interval_seconds = excluded.refresh_interval_seconds
`

func (q *Queries) SetRefreshInterval(ctx context.Context, refreshIntervalSeconds int64) error {
	_, err := q.db.ExecContext(ctx, setRefreshInterval, refreshIntervalSeconds)
	return err
}

const setTasksSyncedAt = `-- name: SetTasksSyncedAt :exec
INSERT INTO app_settings (id, tasks_synced_at)
VALUES (1, ?)
ON CONFLICT(id) DO UPDATE SET tasks_synced_at = excluded.tasks_synced_at
`

func (q *Queries) SetTasksSyncedAt(ctx context.Context, tasksSyncedAt *string) error {
	_, err := q.db.ExecContext(ctx, setTasksSyncedAt, tasksSyncedAt)
	return err
}

const upsertSettings = `-- name: UpsertSettings :exec
INSERT INTO app_settings (id, refresh_interval_seconds, tasks_synced_at)
VALUES (1, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    refresh_interval_seconds = excluded.refresh_interval_seconds,
    tasks_synced_at          = excluded.tasks_synced_at
`

type UpsertSettingsParams struct {
	RefreshIntervalSeconds int64   `json:"refresh_interval_seconds"`
	TasksSyncedAt          *string `json:"tasks_synced_at"`
}

func (q *Queries) UpsertSettings(ctx context.Context, arg UpsertSettingsParams) error {
	_, err := q.db.ExecContext(ctx, upsertSettings, arg.RefreshIntervalSeconds, arg.TasksSyncedAt)
	return err
}
