// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: team.sql

package sqlc

import (
	"context"
)

const deleteTeamBoard = `-- name: DeleteTeamBoard :exec
DELETE FROM team_board WHERE id = ?
`

func (q *Queries) DeleteTeamBoard(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTeamBoard, id)
	return err
}

const deleteTeamBoardDays = `-- name: DeleteTeamBoardDays :exec
DELETE FROM team_board_day WHERE board_id = ?
`

func (q *Queries) DeleteTeamBoardDays(ctx context.Context, boardID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTeamBoardDays, boardID)
	return err
}

const deleteTeamBoardMembers = `-- name: DeleteTeamBoardMembers :exec
DELETE FROM team_board_member WHERE board_id = ?
`

func (q *Queries) DeleteTeamBoardMembers(ctx context.Context, boardID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTeamBoardMembers, boardID)
	return err
}

const deleteTeamBoardProjects = `-- name: DeleteTeamBoardProjects :exec
DELETE FROM team_board_project WHERE board_id = ?
`

func (q *Queries) DeleteTeamBoardProjects(ctx context.Context, boardID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTeamBoardProjects, boardID)
	return err
}

const deleteTeamBoardStatuses = `-- name: DeleteTeamBoardStatuses :exec
DELETE FROM team_board_status WHERE board_id = ?
`

func (q *Queries) DeleteTeamBoardStatuses(ctx context.Context, boardID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTeamBoardStatuses, boardID)
	return err
}

const deleteTeamBoardTasks = `-- name: DeleteTeamBoardTasks :exec
DELETE FROM team_board_task WHERE board_id = ?
`

func (q *Queries) DeleteTeamBoardTasks(ctx context.Context, boardID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTeamBoardTasks, boardID)
	return err
}

const getTeamBoard = `-- name: GetTeamBoard :one
SELECT id, kind, name, position, created_at, updated_at FROM team_board WHERE id = ?
`

func (q *Queries) GetTeamBoard(ctx context.Context, id int64) (TeamBoard, error) {
	row := q.db.QueryRowContext(ctx, getTeamBoard, id)
	var i TeamBoard
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTeamBoard = `-- name: InsertTeamBoard :one
INSERT INTO team_board (kind, name, position, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id
`

type InsertTeamBoardParams struct {
	Kind      string `json:"kind"`
	Name      string `json:"name"`
	Position  int64  `json:"position"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

func (q *Queries) InsertTeamBoard(ctx context.Context, arg InsertTeamBoardParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertTeamBoard,
		arg.Kind,
		arg.Name,
		arg.Position,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertTeamBoardDay = `-- name: InsertTeamBoardDay :exec
INSERT INTO team_board_day (
    board_id, emp_id, day, billable_minutes, non_billable_minutes
) VALUES (?, ?, ?, ?, ?)
`

type InsertTeamBoardDayParams struct {
	BoardID            int64  `json:"board_id"`
	EmpID              int64  `json:"emp_id"`
	Day                string `json:"day"`
	BillableMinutes    int64  `json:"billable_minutes"`
	NonBillableMinutes int64  `json:"non_billable_minutes"`
}

func (q *Queries) InsertTeamBoardDay(ctx context.Context, arg InsertTeamBoardDayParams) error {
	_, err := q.db.ExecContext(ctx, insertTeamBoardDay,
		arg.BoardID,
		arg.EmpID,
		arg.Day,
		arg.BillableMinutes,
		arg.NonBillableMinutes,
	)
	return err
}

const insertTeamBoardMember = `-- name: InsertTeamBoardMember :exec
INSERT INTO team_board_member (board_id, emp_id, emp_name) VALUES (?, ?, ?)
`

type InsertTeamBoardMemberParams struct {
	BoardID int64  `json:"board_id"`
	EmpID   int64  `json:"emp_id"`
	EmpName string `json:"emp_name"`
}

func (q *Queries) InsertTeamBoardMember(ctx context.Context, arg InsertTeamBoardMemberParams) error {
	_, err := q.db.ExecContext(ctx, insertTeamBoardMember, arg.BoardID, arg.EmpID, arg.EmpName)
	return err
}

const insertTeamBoardProject = `-- name: InsertTeamBoardProject :exec
INSERT INTO team_board_project (board_id, project_id, project_code, project_name)
VALUES (?, ?, ?, ?)
`

type InsertTeamBoardProjectParams struct {
	BoardID     int64  `json:"board_id"`
	ProjectID   int64  `json:"project_id"`
	ProjectCode string `json:"project_code"`
	ProjectName string `json:"project_name"`
}

func (q *Queries) InsertTeamBoardProject(ctx context.Context, arg InsertTeamBoardProjectParams) error {
	_, err := q.db.ExecContext(ctx, insertTeamBoardProject,
		arg.BoardID,
		arg.ProjectID,
		arg.ProjectCode,
		arg.ProjectName,
	)
	return err
}

const insertTeamBoardStatus = `-- name: InsertTeamBoardStatus :exec
INSERT INTO team_board_status (board_id, status_id, status_name) VALUES (?, ?, ?)
`

type InsertTeamBoardStatusParams struct {
	BoardID    int64  `json:"board_id"`
	StatusID   int64  `json:"status_id"`
	StatusName string `json:"status_name"`
}

func (q *Queries) InsertTeamBoardStatus(ctx context.Context, arg InsertTeamBoardStatusParams) error {
	_, err := q.db.ExecContext(ctx, insertTeamBoardStatus, arg.BoardID, arg.StatusID, arg.StatusName)
	return err
}

const insertTeamBoardTask = `-- name: InsertTeamBoardTask :exec
INSERT INTO team_board_task (
    board_id, emp_id, task_id, short_code, name, project_code, project_name,
    priority, status_id, status_type, status_color,
    due_date, modified_on, sprint_name, competency_name, synced_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertTeamBoardTaskParams struct {
	BoardID        int64  `json:"board_id"`
	EmpID          int64  `json:"emp_id"`
	TaskID         int64  `json:"task_id"`
	ShortCode      string `json:"short_code"`
	Name           string `json:"name"`
	ProjectCode    string `json:"project_code"`
	ProjectName    string `json:"project_name"`
	Priority       string `json:"priority"`
	StatusID       int64  `json:"status_id"`
	StatusType     string `json:"status_type"`
	StatusColor    string `json:"status_color"`
	DueDate        string `json:"due_date"`
	ModifiedOn     string `json:"modified_on"`
	SprintName     string `json:"sprint_name"`
	CompetencyName string `json:"competency_name"`
	SyncedAt       string `json:"synced_at"`
}

func (q *Queries) InsertTeamBoardTask(ctx context.Context, arg InsertTeamBoardTaskParams) error {
	_, err := q.db.ExecContext(ctx, insertTeamBoardTask,
		arg.BoardID,
		arg.EmpID,
		arg.TaskID,
		arg.ShortCode,
		arg.Name,
		arg.ProjectCode,
		arg.ProjectName,
		arg.Priority,
		arg.StatusID,
		arg.StatusType,
		arg.StatusColor,
		arg.DueDate,
		arg.ModifiedOn,
		arg.SprintName,
		arg.CompetencyName,
		arg.SyncedAt,
	)
	return err
}

const listTeamBoardDays = `-- name: ListTeamBoardDays :many
SELECT board_id, emp_id, day, billable_minutes, non_billable_minutes FROM team_board_day ORDER BY board_id, emp_id, day
`

func (q *Queries) ListTeamBoardDays(ctx context.Context) ([]TeamBoardDay, error) {
	rows, err := q.db.QueryContext(ctx, listTeamBoardDays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeamBoardDay{}
	for rows.Next() {
		var i TeamBoardDay
		if err := rows.Scan(
			&i.BoardID,
			&i.EmpID,
			&i.Day,
			&i.BillableMinutes,
			&i.NonBillableMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamBoardMembers = `-- name: ListTeamBoardMembers :many
SELECT board_id, emp_id, emp_name FROM team_board_member ORDER BY board_id, emp_name, emp_id
`

func (q *Queries) ListTeamBoardMembers(ctx context.Context) ([]TeamBoardMember, error) {
	rows, err := q.db.QueryContext(ctx, listTeamBoardMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeamBoardMember{}
	for rows.Next() {
		var i TeamBoardMember
		if err := rows.Scan(&i.BoardID, &i.EmpID, &i.EmpName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamBoardProjects = `-- name: ListTeamBoardProjects :many
SELECT board_id, project_id, project_code, project_name FROM team_board_project ORDER BY board_id, project_code
`

func (q *Queries) ListTeamBoardProjects(ctx context.Context) ([]TeamBoardProject, error) {
	rows, err := q.db.QueryContext(ctx, listTeamBoardProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeamBoardProject{}
	for rows.Next() {
		var i TeamBoardProject
		if err := rows.Scan(
			&i.BoardID,
			&i.ProjectID,
			&i.ProjectCode,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamBoardStatuses = `-- name: ListTeamBoardStatuses :many
SELECT board_id, status_id, status_name FROM team_board_status ORDER BY board_id, status_name, status_id
`

func (q *Queries) ListTeamBoardStatuses(ctx context.Context) ([]TeamBoardStatus, error) {
	rows, err := q.db.QueryContext(ctx, listTeamBoardStatuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeamBoardStatus{}
	for rows.Next() {
		var i TeamBoardStatus
		if err := rows.Scan(&i.BoardID, &i.StatusID, &i.StatusName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamBoardTasks = `-- name: ListTeamBoardTasks :many
SELECT board_id, emp_id, task_id, short_code, name, project_code, project_name, priority, status_id, status_type, status_color, due_date, modified_on, sprint_name, competency_name, synced_at FROM team_board_task
ORDER BY
    board_id,
    emp_id,
    CASE WHEN due_date = '' THEN 1 ELSE 0 END,
    due_date,
    modified_on DESC
`

// Soonest due first, undated last, newest-modified breaking ties: the same
// order as ListMyTasks, so a board reads like the my-tasks list does.
//
// Keep this file pure ASCII. sqlc's star expansion computes the offset of the
// `*` in bytes but slices the query in runes, so a single non-ASCII character
// anywhere above shifts the splice and emits nonsense like "SELECboard_id".
func (q *Queries) ListTeamBoardTasks(ctx context.Context) ([]TeamBoardTask, error) {
	rows, err := q.db.QueryContext(ctx, listTeamBoardTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeamBoardTask{}
	for rows.Next() {
		var i TeamBoardTask
		if err := rows.Scan(
			&i.BoardID,
			&i.EmpID,
			&i.TaskID,
			&i.ShortCode,
			&i.Name,
			&i.ProjectCode,
			&i.ProjectName,
			&i.Priority,
			&i.StatusID,
			&i.StatusType,
			&i.StatusColor,
			&i.DueDate,
			&i.ModifiedOn,
			&i.SprintName,
			&i.CompetencyName,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamBoards = `-- name: ListTeamBoards :many
SELECT id, kind, name, position, created_at, updated_at FROM team_board ORDER BY position, id
`

func (q *Queries) ListTeamBoards(ctx context.Context) ([]TeamBoard, error) {
	rows, err := q.db.QueryContext(ctx, listTeamBoards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeamBoard{}
	for rows.Next() {
		var i TeamBoard
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTeamBoardPosition = `-- name: SetTeamBoardPosition :exec
UPDATE team_board SET position = ?, updated_at = ? WHERE id = ?
`

type SetTeamBoardPositionParams struct {
	Position  int64  `json:"position"`
	UpdatedAt string `json:"updated_at"`
	ID        int64  `json:"id"`
}

func (q *Queries) SetTeamBoardPosition(ctx context.Context, arg SetTeamBoardPositionParams) error {
	_, err := q.db.ExecContext(ctx, setTeamBoardPosition, arg.Position, arg.UpdatedAt, arg.ID)
	return err
}

const setTeamSyncedAt = `-- name: SetTeamSyncedAt :exec
INSERT INTO app_settings (id, team_synced_at)
VALUES (1, ?)
ON CONFLICT(id) DO UPDATE SET team_synced_at = excluded.team_synced_at
`

func (q *Queries) SetTeamSyncedAt(ctx context.Context, teamSyncedAt *string) error {
	_, err := q.db.ExecContext(ctx, setTeamSyncedAt, teamSyncedAt)
	return err
}

const updateTeamBoard = `-- name: UpdateTeamBoard :exec
UPDATE team_board SET name = ?, position = ?, updated_at = ? WHERE id = ?
`

type UpdateTeamBoardParams struct {
	Name      string `json:"name"`
	Position  int64  `json:"position"`
	UpdatedAt string `json:"updated_at"`
	ID        int64  `json:"id"`
}

// kind is not updatable: switching a board's kind would leave the wrong cache
// table populated and the wrong filters saved. Delete and recreate instead.
func (q *Queries) UpdateTeamBoard(ctx context.Context, arg UpdateTeamBoardParams) error {
	_, err := q.db.ExecContext(ctx, updateTeamBoard,
		arg.Name,
		arg.Position,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
