// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Bootstrap():Promise<main.BootstrapResult>;

export function Info():Promise<main.AppInfo>;

export function SetDisplayName(arg1:string):Promise<void>;

export function SignIn(arg1:string,arg2:string):Promise<main.SignInResult>;

export function SignOut():Promise<void>;
