// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Bootstrap() {
  return window['go']['main']['App']['Bootstrap']();
}

export function GetBilling() {
  return window['go']['main']['App']['GetBilling']();
}

export function GetBillingForDate(arg1) {
  return window['go']['main']['App']['GetBillingForDate'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function Info() {
  return window['go']['main']['App']['Info']();
}

export function ListTasks() {
  return window['go']['main']['App']['ListTasks']();
}

export function MarkTasksSeen() {
  return window['go']['main']['App']['MarkTasksSeen']();
}

export function OpenTask(arg1, arg2) {
  return window['go']['main']['App']['OpenTask'](arg1, arg2);
}

export function RefreshBilling() {
  return window['go']['main']['App']['RefreshBilling']();
}

export function RefreshTasks() {
  return window['go']['main']['App']['RefreshTasks']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetDisplayName(arg1) {
  return window['go']['main']['App']['SetDisplayName'](arg1);
}

export function SignIn(arg1, arg2) {
  return window['go']['main']['App']['SignIn'](arg1, arg2);
}

export function SignOut() {
  return window['go']['main']['App']['SignOut']();
}
