// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Bootstrap() {
  return window['go']['main']['App']['Bootstrap']();
}

export function DeleteMonitor(arg1) {
  return window['go']['main']['App']['DeleteMonitor'](arg1);
}

export function GetBilling() {
  return window['go']['main']['App']['GetBilling']();
}

export function GetBillingForDate(arg1) {
  return window['go']['main']['App']['GetBillingForDate'](arg1);
}

export function GetMonitor(arg1) {
  return window['go']['main']['App']['GetMonitor'](arg1);
}

export function GetMyTasksFilter() {
  return window['go']['main']['App']['GetMyTasksFilter']();
}

export function GetMyTasksOptions() {
  return window['go']['main']['App']['GetMyTasksOptions']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function HideMyTask(arg1) {
  return window['go']['main']['App']['HideMyTask'](arg1);
}

export function Info() {
  return window['go']['main']['App']['Info']();
}

export function ListMonitors() {
  return window['go']['main']['App']['ListMonitors']();
}

export function ListMyTasks() {
  return window['go']['main']['App']['ListMyTasks']();
}

export function ListProjectMembers(arg1) {
  return window['go']['main']['App']['ListProjectMembers'](arg1);
}

export function ListSelectableProjects() {
  return window['go']['main']['App']['ListSelectableProjects']();
}

export function ListTasks() {
  return window['go']['main']['App']['ListTasks']();
}

export function MarkMyTasksSeen() {
  return window['go']['main']['App']['MarkMyTasksSeen']();
}

export function MarkTasksSeen() {
  return window['go']['main']['App']['MarkTasksSeen']();
}

export function OpenTask(arg1, arg2) {
  return window['go']['main']['App']['OpenTask'](arg1, arg2);
}

export function RefreshBilling() {
  return window['go']['main']['App']['RefreshBilling']();
}

export function RefreshMonitors() {
  return window['go']['main']['App']['RefreshMonitors']();
}

export function RefreshMyTasks() {
  return window['go']['main']['App']['RefreshMyTasks']();
}

export function RefreshTasks() {
  return window['go']['main']['App']['RefreshTasks']();
}

export function SaveMonitor(arg1) {
  return window['go']['main']['App']['SaveMonitor'](arg1);
}

export function SaveMyTasksFilter(arg1) {
  return window['go']['main']['App']['SaveMyTasksFilter'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetDisplayName(arg1) {
  return window['go']['main']['App']['SetDisplayName'](arg1);
}

export function SignIn(arg1, arg2) {
  return window['go']['main']['App']['SignIn'](arg1, arg2);
}

export function SignOut() {
  return window['go']['main']['App']['SignOut']();
}

export function UnhideAllMyTasks() {
  return window['go']['main']['App']['UnhideAllMyTasks']();
}

export function UnhideMyTask(arg1) {
  return window['go']['main']['App']['UnhideMyTask'](arg1);
}
