// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {billing} from '../models';
import {settings} from '../models';

export function Bootstrap():Promise<main.BootstrapResult>;

export function GetBilling():Promise<main.BillingResult>;

export function GetBillingForDate(arg1:string):Promise<billing.DayTotal>;

export function GetSettings():Promise<settings.Settings>;

export function Info():Promise<main.AppInfo>;

export function ListTasks():Promise<main.TasksResult>;

export function MarkTasksSeen():Promise<void>;

export function OpenTask(arg1:number,arg2:string):Promise<void>;

export function RefreshBilling():Promise<main.BillingResult>;

export function RefreshTasks():Promise<main.TasksResult>;

export function SaveSettings(arg1:settings.Settings):Promise<settings.Settings>;

export function SetDisplayName(arg1:string):Promise<void>;

export function SignIn(arg1:string,arg2:string):Promise<main.SignInResult>;

export function SignOut():Promise<void>;
