// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Bootstrap() {
  return window['go']['main']['App']['Bootstrap']();
}

export function Info() {
  return window['go']['main']['App']['Info']();
}

export function SetDisplayName(arg1) {
  return window['go']['main']['App']['SetDisplayName'](arg1);
}

export function SignIn(arg1, arg2) {
  return window['go']['main']['App']['SignIn'](arg1, arg2);
}

export function SignOut() {
  return window['go']['main']['App']['SignOut']();
}
