// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {billing} from '../models';
import {monitor} from '../models';
import {mytasks} from '../models';
import {settings} from '../models';
import {team} from '../models';
import {pinestem} from '../models';

export function Bootstrap():Promise<main.BootstrapResult>;

export function DeleteMonitor(arg1:number):Promise<void>;

export function DeleteTeamBoard(arg1:number):Promise<void>;

export function GetBilling():Promise<main.BillingResult>;

export function GetBillingForDate(arg1:string):Promise<billing.DayTotal>;

export function GetMonitor(arg1:number):Promise<monitor.Monitor>;

export function GetMyTasksFilter():Promise<mytasks.Filter>;

export function GetMyTasksOptions():Promise<mytasks.Options>;

export function GetSettings():Promise<settings.Settings>;

export function GetTeamBoard(arg1:number):Promise<team.Board>;

export function HideMyTask(arg1:number):Promise<void>;

export function Info():Promise<main.AppInfo>;

export function ListMonitors():Promise<main.MonitorsResult>;

export function ListMyTasks():Promise<main.MyTasksResult>;

export function ListProjectMembers(arg1:Array<string>):Promise<Array<pinestem.Member>>;

export function ListSelectableProjects():Promise<Array<pinestem.Project>>;

export function ListTasks():Promise<main.TasksResult>;

export function ListTeamBoards():Promise<main.TeamResult>;

export function ListTeamMembers(arg1:Array<string>):Promise<Array<pinestem.Member>>;

export function ListTeamStatuses(arg1:Array<string>):Promise<Array<pinestem.TaskStatus>>;

export function MarkMyTasksSeen():Promise<void>;

export function MarkTasksSeen():Promise<void>;

export function OpenTask(arg1:number,arg2:string):Promise<void>;

export function RefreshBilling():Promise<main.BillingResult>;

export function RefreshMonitors():Promise<main.MonitorsResult>;

export function RefreshMyTasks():Promise<main.MyTasksResult>;

export function RefreshTasks():Promise<main.TasksResult>;

export function RefreshTeamBoards():Promise<main.TeamResult>;

export function ReorderTeamBoards(arg1:Array<number>):Promise<void>;

export function SaveMonitor(arg1:monitor.Monitor):Promise<monitor.Monitor>;

export function SaveMyTasksFilter(arg1:mytasks.Filter):Promise<mytasks.Filter>;

export function SaveSettings(arg1:settings.Settings):Promise<settings.Settings>;

export function SaveTeamBoard(arg1:team.Board):Promise<team.Board>;

export function SetDisplayName(arg1:string):Promise<void>;

export function SignIn(arg1:string,arg2:string):Promise<main.SignInResult>;

export function SignOut():Promise<void>;

export function UnhideAllMyTasks():Promise<void>;

export function UnhideMyTask(arg1:number):Promise<void>;
